### ISSUE TITLE
Cannot create a policy with permissions over multiple types of resources

### ISSUE THREAD

**Issue by Kamil-Stachura** [oracle-quickstart/terraform-oci-cis-landing-zone-iam#6]
When trying to create a policy that will provide a group with permissions over multiple types of resources (database, exainfra, storage, enclosing, application) within a single compartment, the module attempts to create a separate policy with the same name for each type of resource. This causes a Terraform error, as creating multiple policies with the same name is not allowed.

Snippet from compartments config code:
  "CMP-INSURANCE-PROD": {
      "name": "cmp-insurance-prod",
      "description": "Insurance Prod Compartment",
      "defined_tags": null,
      "freeform_tags": {
          "cislz": "sagauks-insurance",
          "cislz-cmp-type": "database,exainfra,storage,enclosing,application,",
          "cislz-consumer-groups-database": "sagauks-insurance-prod-resources-admin-group",
          "cislz-consumer-groups-exainfra": "sagauks-insurance-prod-resources-admin-group",
          "cislz-consumer-groups-storage": "sagauks-insurance-prod-resources-admin-group",
          "cislz-consumer-groups-application": "sagauks-insurance-prod-resources-admin-group"
      },

Snippet from groups config code:
  "INSURANCE-PROD-RESOURCES-ADMIN-GROUP": {
      "defined_tags": null,
      "description": "CIS Landing Zone Insurance Production Application Resources administrators group.",
      "freeform_tags": null,
      "members": [],
      "name": "sagauks-insurance-prod-resources-admin-group"
  },

Snippet from policies config code:
  "policies_configuration": {
      "enable_compartment_level_template_policies": "true",
      "cislz_tag_lookup_value": "sagauks-insurance",
      "enable_tenancy_level_template_policies": "true",
      "groups_with_tenancy_level_roles": [],
      "custom_policies": {},
      "enable_cis_benchmark_checks": "true",
      "defined_tags": null,
      "freeform_tags": null,
      "policy_name_prefix": null,
      "enable_output": true,
      "enable_debug": false
  }

To test how to resolve the issue, I have modified the following files in https://github.com/oracle-quickstart/terraform-oci-cis-landing-zone-iam/tree/main/policies:
application_cmp_policy.tf - altered the name definition in local.application_cmps_policies
database_cmp_policy.tf - altered the name definition in local.database_cmps_policies
enclosing_cmp_policy.tf - altered the name definition in local.enclosing_cmps_policies
exainfra_cmp_policy.tf - altered the name definition in local.exainfra_cmps_policies
network_cmp_policy.tf - altered the name definition in local.network_cmps_policies

Example of the modification made:
  #-- Policies - MODIFIED
  application_cmps_policies = {for cmp, values in local.cmp_name_to_cislz_tag_map : 
    (upper("${cmp}-application-policy")) => {
      name             = "${local.policy_name_prefix}${cmp}-application${local.policy_name_suffix}"
      compartment_ocid = values.ocid
      description      = "CIS Landing Zone policy for Application compartment."
      defined_tags     = var.policies_configuration.defined_tags
      freeform_tags    = var.policies_configuration.freeform_tags
      statements       = concat(local.application_admin_grants_on_application_cmp_map[cmp],local.application_read_grants_on_application_cmp_map[cmp],
                              local.storage_admin_grants_on_application_cmp_map[cmp],local.compute_agent_grants_on_application_cmp_map[cmp])
    }
  }

Another potential solution could be to modify the module so that policies for different resources are iterated over and merged into a single policy if these match on the compartment id, so that a single policy can be created for multiple types of resources within the same compartment, which will avoid the error of attempting to create multiple policies with the same name.

**Comment by andrecorreaneto** [comment]
Thanks for the detailed diagnosis.
It has been fixed.
